### ISSUE TITLE
xsd:sequence en validatie-errors

### ISSUE THREAD

**Issue by dhvenema** [aerius/IMAER#12]
Bij het zelf aanmaken van GML's liep ik verschillende moment tegen cryptische validatie errors aan. Na enig onderzoek in de xsd zag ik dat op verschillende punten een `xsd:sequence` gebruikt, hierdoor is de volgorde waarin de element voorkomen van belang. Zie bijvoorbeeld: https://github.com/aerius/IMAER/blob/master/gmlapplicatieschema/4.0.0/IMAER.xsd#L1860. 

Is er een specifieke reden waarom dit is gedaan? Want dit maakt de GML (lijkt me) foutgevoeliger. In tegenstelling, met `xsd:all` zou bv. de volgorde niet van belang zijn.

**Comment by BertScholten** [comment]
Er zijn enkele redenen waarom er gebruik wordt gemaakt van `xsd:sequence`:

In GML is het gebruikelijk om `xsd:sequence` te gebruiken, dit wordt bijvoorbeeld ook gebruikt in het `gml:AbstractFeatureType` (http://schemas.opengis.net/gml/3.2.1/feature.xsd) object waar veel van onze objecten op zijn gebaseerd. Ook de andere informatiemodellen onder NEN3610 maken hier gebruik van (zie https://register.geostandaarden.nl/).

Een nadeel van het gebruik van `xsd:all` is dat daarmee geen gebruik gemaakt kan worden van het erfen (`xsd:extension`) van objecten, in ieder geval niet in XSD 1.0. Dit wordt in GML (en IMAER) vrij veel gebruikt.

Daarnaast gebruiken we een tool om de XSD te genereren vanuit het EAP document. Hierbij wordt ook deze constructie gebruikt.

**Comment by dhvenema** [comment]
Ok, dan zal ik de volgorde van de elementen zelf goed zetten. Bedankt voor het antwoorden!
