### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by WebWire-NL** [aerius/IMAER#5]
Hi,
Can you point me to the open source parts for Aerius, it's mentioned everywhere but even google doesn't find any related open source :)

"AERIUS hoort bij de laatste 4 kanshebbers op de ‘Sharing and Reuse Award’. " I hope this is more then available in the aerius repositories?

**Comment by WebWire-NL** [comment]
i'll answer my own question :)
for anyone else looking for aerius....
https://gitlab.com/AERIUS

First question.... looks like the source hasnt been updated since  Release 2016.1.6 (last release 3 weeks ago). How do we know if this is the latest source? looks like something changed a couple weeks ago https://www.aerius.nl/nl/organisatie/aerius-team ;) google cache is out friend

**Comment by Hilbrand** [comment]
Apparently this question remained unaswered for a very long time, possible as this repository is only used to publish the xsd's. Sorry for that. To answer your first question. In general it's the intention to update the source code when new releases are done.
